# Conda environment file, works with the openscene project.
# Assumes that CUDA 12.1 is installed.
name: cm3d
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.0
  - mkl-include

  # meta-package, to choose the right pytorch package
  - pytorch::pytorch-cuda=12.1
  - pytorch::pytorch=2.2.*
  - torchvision=0.17.*

  - scipy
  - open3d
  - ftfy
  - tensorboardx
  - tqdm
  - imageio
  - plyfile
  - opencv
  - sharedarray

  - pip:
    - git+https://github.com/openai/CLIP.git
