hydra:
  job:
    name: instance_masks_from_images
    chdir: false
  run:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
samples: 20
resized_img_width: 400
resized_img_height: 300
sam_model_type: vit_h
sam_checkpoint: /media/papjuli/Data/data/3DV_project/openmask3d_resources/sam_vit_h_4b8939.pth
sam_mask_gen_params:
  # points_per_side: 32
  pred_iou_thresh: 0.82
  stability_score_thresh: 0.87
  crop_n_layers: 2
  crop_n_points_downscale_factor: 2
  min_mask_region_area: 50  # Requires open-cv to run post-processing
scene:
  point_cloud_path: /media/papjuli/Data/data/3DV_project/STPLS3D/point_clouds/RealWorldData/WMSC_points.ply
  cam_info_path: /media/papjuli/Data/data/3DV_project/STPLS3D/Source_Images/Real_World/WMSC_CamInfoCC.xml
  images_dir: /media/papjuli/Data/data/3DV_project/STPLS3D/Source_Images/Real_World/WMSC
  mesh_path: /media/papjuli/Data/data/3DV_project/processed/STPLS3D/mesh/WMSC.ply
  visibility_threshold: 0.98
