input_dir: /media/papjuli/Data/data/3DV_project/STPLS3D/Source_Images/Real_World/RA
output_dir: Instance_Masks_test/Real_World/RA
samples: 10
resized_img_width: 400
resized_img_height: 300
sam_model_type: vit_h
sam_checkpoint: /media/papjuli/Data/data/3DV_project/openmask3d_resources/sam_vit_h_4b8939.pth
sam_mask_gen_params:
  # points_per_side: 32
  pred_iou_thresh: 0.75
  stability_score_thresh: 0.8
  crop_n_layers: 2
  crop_n_points_downscale_factor: 2
  min_mask_region_area: 100  # Requires open-cv to run post-processing
