hydra:
  job:
    name: instance_masks_from_images
    chdir: false
  run:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
samples: 0  # 10
start_from_img: null
end_at_img: null
resized_img_width: 400
resized_img_height: 300
sam_model_type: vit_h
sam_checkpoint: /media/papjuli/Data/data/3DV_project/openmask3d_resources/sam_vit_h_4b8939.pth
image_text_model: openai/clip-vit-base-patch32
crop_margin: 30
debug: false  #true
sam_mask_gen_params:
  points_per_side: 24
  pred_iou_thresh: 0.9
  stability_score_thresh: 0.95
  crop_n_layers: 1
  crop_n_points_downscale_factor: 2
  min_mask_region_area: 50  # Requires open-cv to run post-processing
scene:
  # point_cloud_path: /media/papjuli/Data/data/3DV_project/STPLS3D/point_clouds/RealWorldData/RA_points.ply
  point_cloud_path: /media/papjuli/Data/data/3DV_project/processed/STPLS3D/mesh/RA_1M.ply
  cam_info_path: /media/papjuli/Data/data/3DV_project/STPLS3D/Source_Images/Real_World/RA_CamInfoCC.xml
  images_dir: /media/papjuli/Data/data/3DV_project/STPLS3D/Source_Images/Real_World/RA
  mesh_path: /media/papjuli/Data/data/3DV_project/processed/STPLS3D/mesh/RA_1M.ply
  visibility_threshold: 0.98
