hydra:
  job:
    name: merge_masks
    chdir: false
  run:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
# input_dir: /home/papjuli/code/ETH/3DV_project/CityMagic3D/outputs/instance_masks_from_images/2024-05-18_22-01-35/
# input_dir: /home/papjuli/code/ETH/3DV_project/CityMagic3D/outputs/instance_masks_from_images/2024-05-20_15-36-55/
input_dir: /home/papjuli/code/ETH/3DV_project/CityMagic3D/outputs/instance_masks_from_images/2024-05-20_22-52-38/
cam_info_path: /media/papjuli/Data/data/3DV_project/STPLS3D/Source_Images/Real_World/RA_CamInfoCC.xml
min_intersection_ratio: 0.5
view_depth: 50
